299 refactoring renaming property cluster 03
ebu/ebucoreplus pull request #331
Opened 2024-06-04 12:02 UTC by alexander-schulze

This pull request includes the renaming of ten object properties.

- 'isMeasuredBy' to 'hasMeasurementAgent'
- 'isRegisteredAs' to 'uses'
- 'isReleasedBy' to 'isOrderedBy'
- 'isResourceCommissionedBy' to 'isCommissionedBy'.
- 'isScheduledOn' to 'isPublishedBy'.
- 'hasLinkToLogo' to 'hasLogo'
- 'hasLinkToSticker' to 'hasSticker'.
- 'hasLocationRegion' to 'hasRegionCode'.
- 'logsPublicationEvent' to 'logs'.
- 'hasMeasureValueUnit' object property to 'hasUnit'

**Reviewers:**
- @JuergenGrupp
- @aro-max

2024-06-10 06:12 UTC, alexander-schulze commented
@JuergenGrupp @aro-max 
Looking forward to your feedback.

2024-06-10 11:08 UTC, JuergenGrupp requested changes
Thank you @alexander-schulze !
Looks very good to me, exactly as requested. 

However, I found one name that needs further improvement:
instead of renaming `hasRegisteredAs` to `uses` 
I would now rather rename it to `hasRegistration`.

That fits much better to the description and is more precise than `uses`
Please add this change, thank you!

2024-06-10 12:00 UTC, alexander-schulze commented
@JuergenGrupp 
The object property name has been changed from `uses` to `hasRegistration`.

2024-06-16 15:50 UTC, aro-max commented
Thank you @alexander-schulze I agree with @JuergenGrupp about 'uses', I have some questions : 

isReleasedBy' to 'isOrderedBy': 'isOrderedBy' seems to shift the focus to the ordering entity, which may not always be the releasing entity.

isReleasedBy: Indicates the entity that made the resource available to the public.
isOrderedBy: Implies the entity that requested or initiated the creation or distribution of the resource.

isScheduledOn' to 'isPublishedBy': This change specifies the entity responsible for publishing, which may be different from scheduling. Typically for publication on platforms 

logsPublicationEvent' to 'logs': This simplifies the property name, but may lose some specificity regarding what is being logged. It could be logsPublication.

2024-06-17 16:10 UTC, merged